[package]
name = "libunftp"
version = "0.8.0"
authors = [
    "Agoston Horvath <ahorvath@bol.com>",
    "Dávid Kosztka <dkosztka@bol.com>",
    "Hannes de Jager <hdejager@bol.com>",
    "Koen Wilde <koen@chillheid.nl>",
    "Maarten Dirkse <mdirkse@bol.com>",
    "Steven Meunier <smeunier@bol.com>",
    "Rob klein Gunnewiek <rkleingunnewiek@bol.com>",
   ]
description = "Safe, fast and extensible FTP(S) server library for Rust."
documentation = "https://docs.rs/libunftp/"
repository = "https://github.com/bolcom/libunftp"
license = "Apache-2.0"
readme = "README.md"
keywords = ["ftp", "ftps"]
categories = ["network-programming"]
edition = "2018"

[dependencies]
async-trait = "0.1.30"
regex = "1.3.6"
futures = {version = "0.3.4", features = ["compat", "io-compat", "std"]}
tokio = { version = "0.2.17", features = ["rt-core", "net", "sync", "io-util", "macros", "time", "fs"]}
tokio-util = { version = "0.3.1", features=["codec"] }
tokio-tls = { version = "0.3.0" }
native-tls = "0.2.4"
rustls = "0.17.0"
bytes = "0.5.4"
lazy_static = "1.4.0"
log = "0.4.8"
chrono = {version = "0.4.11", features = ["serde"]}
failure = "0.1.7"
failure_derive = "0.1.7"
pam-auth = { package = "pam", version = "0.7.0", optional = true }
hyper = { version = "0.13.4", optional = true }
percent-encoding = { version = "2.1.0", optional = true }
http = { version = "0.2.1", optional = true }
serde = { version = "1.0.106", optional = true, features = ["derive"] }
serde_json = { version = "1.0.51", optional = true }
path_abs = "0.5.0"
prometheus = "0.8.0"
uuid = { version = "0.8.1", features = ["v4"] }
rand = "0.7.3"

hyper-rustls = {version = "0.20.0", optional = true}
yup-oauth2 = {version = "4.1.0", optional = true}
mime = {version = "0.3.16", optional = true}
itertools = "0.9.0"
proxy-protocol = {version = "0.1.1"}
chashmap = {version = "2.2.2"}

[dev-dependencies]
tempfile = "3.1.0"
ftp = "3.0.1"
pretty_env_logger = "0.4.0"
pretty_assertions = "0.6.1"
tokio = { version = "0.2.17", features = ["rt-threaded"]}

[features]
pam_auth = ["pam-auth"]
rest_auth = ["hyper", "percent-encoding", "http", "serde", "serde_json"]
jsonfile_auth = ["serde", "serde_json"]
cloud_storage = ["oauth2", "mime", "percent-encoding", "hyper", "serde", "serde_json"]
oauth2 = ["yup-oauth2", "hyper-rustls"]

[[example]]
name = "pam"
required-features = ["pam_auth"]

[[example]]
name = "gcs"
required-features = ["cloud_storage"]

[[example]]
name = "rest"
required-features = ["rest_auth"]

[[example]]
name = "jsonfile_auth"
required-features = ["jsonfile_auth"]
